name: "angel_compiled_mustache"
description: "Compiled Mustache view generator for Angel."
author: "thislooksfun <thislooksfun@repbot.org>"
homepage: "https://github.com/thislooksfun/angel_compiled_mustache"
version: "1.1.0"
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  angel_framework: "^1.0.0-dev"
  compiled_mustache: "^1.0.1"
  path: "^1.5.0"
  file: "^2.0.0"
dev_dependencies:
  test: "^0.12.13"
  grinder: "^0.8.0"